# Configuración básica para Jekyll
title: "Proyecto Guía - Diseño Digital 5"
description: "Template base para el primer bloque del curso"
baseurl: "/centro-template"
url: "https://juanfuent-es.github.io"

# Configuración básica de Jekyll
markdown: kramdown
highlighter: rouge
theme: minima
